### ISSUE TITLE
Gramps crashes when the plugin is present and only with some people, but not all.

### ISSUE THREAD

**Issue by brinycoolie** [cdhorn/profileview#10]
Error text follows.
804989: ERROR: person_profile.py: line 760: 'NoneType' object has no attribute 'get_child_ref_list'
Traceback (most recent call last):
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/person_profile.py", line 755, in change_person
    return self._change_person(obj)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/person_profile.py", line 822, in _change_person
    timeline = get_timeline_profiles(
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/frame_groups.py", line 258, in get_timeline_profiles
    group = TimelineGrampsFrameGroup(dbstate, uistate, person, router, config)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/frame_timeline.py", line 98, in __init__
    self.timeline.set_person(
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/timeline.py", line 441, in set_person
    timeline, birth, death = self.extract_person_events(person)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/timeline.py", line 412, in extract_person_events
    timeline = self.prepare_event_sortvals(events)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/timeline.py", line 350, in prepare_event_sortvals
    sortval = self.generate_union_event_sortval(family, union=True)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/timeline.py", line 367, in generate_union_event_sortval
    child_handles = family.get_child_ref_list()
AttributeError: 'NoneType' object has no attribute 'get_child_ref_list'

Using latest linux Mint

Thanks for your efforts!

**Comment by brinycoolie** [comment]
New error just now after restarting Gramps.

2989: ERROR: person_profile.py: line 760: 'EventType' object has no attribute 'get_value'
Traceback (most recent call last):
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/person_profile.py", line 755, in change_person
    return self._change_person(obj)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/person_profile.py", line 822, in _change_person
    timeline = get_timeline_profiles(
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/frame_groups.py", line 258, in get_timeline_profiles
    group = TimelineGrampsFrameGroup(dbstate, uistate, person, router, config)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/frame_timeline.py", line 98, in __init__
    self.timeline.set_person(
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/timeline.py", line 442, in set_person
    self.merge_eligible_events(person, timeline, "self", birth=birth, death=death)
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/timeline.py", line 312, in merge_eligible_events
    self.timeline.append((sortval, (event, event_ref, person, relationship, self.get_category(event))))
  File "/home/brian/.gramps/gramps51/plugins/ProfileView/timeline.py", line 241, in get_category
    if event_type.get_value() == event_name:
AttributeError: 'EventType' object has no attribute 'get_value'

**Comment by brinycoolie** [comment]
Have to uninstall the plugin after the above crash from the Plugins directory in order to restart Gramps in order to select a different person. Then when closed it re-opens fine with the new person.

**Comment by cdhorn** [comment]
Thank you for both of those, I think they may be fixed now if you have a chance to check. Please let me know if you run into others.

**Comment by cdhorn** [comment]
Both should be fixed, closing for now.
