### ISSUE TITLE
Copy keybinding causes Unhandled Exception

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#58]
Pressing Crtl-C with the Profile view active causes the following error:

```
1668034: ERROR: grampsapp.py: line 157: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\ProfileView\enavigationview.py", line 498, in key_press_handler
    self.call_copy()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\ProfileView\enavigationview.py", line 513, in call_copy
    return self.copy_to_clipboard(nav_type, handles)
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\gui\views\pageview.py", line 295, in copy_to_clipboard
    -1)  # time
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\gui\clipboard.py", line 1242, in object_drag_data_received
    _ob = wrapper_class(sel_data)
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\gui\clipboard.py", line 721, in __init__
    self.refresh()
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\gui\clipboard.py", line 725, in refresh
    person = clipdb.get_person_from_handle(self._handle)
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\gen\db\generic.py", line 1282, in get_person_from_handle
    return self._get_from_handle(PERSON_KEY, Person, handle)
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\gen\db\generic.py", line 1266, in _get_from_handle
    data = self._get_raw_data(obj_key, handle)
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\plugins\db\dbapi\dbapi.py", line 879, in _get_raw_data
    self.dbapi.execute(sql, [handle])
  File "C:\Program Files\GrampsAIO64-5.1.3-2\gramps\plugins\db\dbapi\sqlite.py", line 131, in execute
    self.__cursor.execute(*args, **kwargs)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

```

**Comment by cdhorn** [comment]
Should be fixed now.
